version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma

  postgres:
    image: postgres:10.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  server:
    build: ./server
    ports:
      - "5000:5000"
    command: sh -c "dockerize -wait http://prisma:4466 -timeout 300s -wait-retry-interval 4s  && prisma1 deploy && npm run start"


  react-apollo:
    build: ./react-apollo
    ports:
      - "3000:3000"
    environment:
      - CI=true
    stdin_open: true


networks:
  default:
    driver: bridge
volumes:
  postgres: ~
